// config-ui/src/sections/PagesSection.svelte
<script lang="ts">
  import type { Settings, Inventory } from "../api";
  import { defaults } from "../api";
  import Sub from "../components/Sub.svelte";
  import Row from "../components/Row.svelte";
  import Slider from "../components/Slider.svelte";
  import Chip from "../components/Chip.svelte";

  export let s: Settings;
  export let set: (p: Partial<Settings>) => void;
  export let inv: Inventory | null = null;

  const EASINGS = ["linear","easeInQuad","easeOutQuad","easeInOutQuad","easeOutCubic","easeInOutCubic","easeOutBack"];

  $: cfg = s.pages ?? defaults.pages;
  $: enabled = new Set(cfg.enabled);

  function toggle(id: string) {
    const next = new Set(enabled);
    if (next.has(id)) next.delete(id); else next.add(id);
    set({ pages: { ...cfg, enabled: Array.from(next) } });
  }

  function setCfg(p: Partial<typeof cfg>) {
    set({ pages: { ...cfg, ...p } });
  }
</script>

<div class="section">
  <Sub num={1} title="Enabled pages" desc="Expanded view: pages available when the pill morphs into a panel.">
    {#if !inv}
      <div class="empty"><span class="spinner" /> Loading…</div>
    {:else}
      <div class="chip-list">
        {#each inv.pages as p}
          <Chip active={enabled.has(p.id)} onClick={() => toggle(p.id)}>{p.label}</Chip>
        {/each}
      </div>
    {/if}
  </Sub>

  <Sub num={2} title="Page transitions" desc="Animation used when expanding the island and switching pages.">
    <Row label="Duration">
      <Slider value={cfg.animations.duration} min={0} max={800} step={10} unit="ms"
              onChange={(v) => setCfg({ animations: { ...cfg.animations, duration: v } })} />
    </Row>
    <Row label="Easing">
      <select value={cfg.animations.easing} on:change={(e) => setCfg({ animations: { ...cfg.animations, easing: e.currentTarget.value } })}>
        {#each EASINGS as e}<option>{e}</option>{/each}
      </select>
    </Row>
  </Sub>
</div>

// config-ui/src/sections/PagesSection.tsx
import React from "react";
import { Settings, Inventory, defaults } from "../api";
import { Sub, Row, Chip, Slider } from "../components/UI";

const EASINGS = ["linear", "easeInQuad", "easeOutQuad", "easeInOutQuad", "easeOutCubic", "easeInOutCubic", "easeOutBack"];

export function PagesSection({
  s,
  set,
  inv,
}: {
  s: Settings;
  set: (p: Partial<Settings>) => void;
  inv: Inventory | null;
}) {
  const cfg = s.pages ?? defaults.pages;
  const setCfg = (p: Partial<typeof cfg>) => set({ pages: { ...cfg, ...p } });
  const enabled = new Set(cfg.enabled);
  const toggle = (id: string) => {
    if (enabled.has(id)) enabled.delete(id);
    else enabled.add(id);
    setCfg({ enabled: Array.from(enabled) });
  };

  return (
    <div className="section">
      <Sub
        num={1}
        title="Enabled pages"
        desc="Expanded view: pages available when the pill morphs into a panel."
      >
        {!inv ? (
          <div className="empty"><span className="spinner" /> Loading…</div>
        ) : (
          <div className="chip-list">
            {inv.pages.map((p) => (
              <Chip key={p.id} active={enabled.has(p.id)} onClick={() => toggle(p.id)}>
                {p.label}
              </Chip>
            ))}
          </div>
        )}
      </Sub>

      <Sub
        num={2}
        title="Page transitions"
        desc="Animation used when expanding the island and switching pages."
      >
        <Row label="Duration">
          <Slider
            value={cfg.animations.duration}
            min={0}
            max={800}
            step={10}
            unit="ms"
            onChange={(v) => setCfg({ animations: { ...cfg.animations, duration: v } })}
          />
        </Row>
        <Row label="Easing">
          <select
            value={cfg.animations.easing}
            onChange={(e) => setCfg({ animations: { ...cfg.animations, easing: e.target.value } })}
          >
            {EASINGS.map((x) => <option key={x}>{x}</option>)}
          </select>
        </Row>
      </Sub>
    </div>
  );
}
