// config-ui/src/sections/ThemeSection.svelte
<script lang="ts">
  import type { Settings } from "../api";
  import Sub from "../components/Sub.svelte";
  import Row from "../components/Row.svelte";
  import Toggle from "../components/Toggle.svelte";
  import Slider from "../components/Slider.svelte";
  import Icon from "../components/Icon.svelte";

  export let s: Settings;
  export let set: (p: Partial<Settings>) => void;
  export let palette: Record<string, string> = {};

  const VARIANTS = [
    { id: "mocha",    name: "Mocha",    desc: "Warm night",      colors: ["#1e1e2e","#cba6f7","#89b4fa","#fab387"] },
    { id: "matugen", name: "Matugen",  desc: "Wallpaper tones", colors: ["#1e1e2e","#c0a8f0","#88b4f8","#f0b070"] },
    { id: "apple",   name: "Apple",    desc: "macOS light",     colors: ["#f5f5f7","#007aff","#34c759","#ff9500"] },
    { id: "nord",    name: "Nord",     desc: "Arctic blue",     colors: ["#2e3440","#88c0d0","#81a1c1","#d08770"] },
    { id: "carbon",  name: "Carbon",   desc: "Graphite dark",   colors: ["#111111","#d4d4d8","#60a5fa","#fdba74"] },
    { id: "midnight",name: "Midnight", desc: "Deep space",      colors: ["#08080f","#7c7cf5","#4fc3f7","#e879f9"] },
  ];

  $: theme = s.theme ?? { mode: s.topbarTheme || "mocha", overrides: {} };
  $: overrides = theme.overrides ?? {};

  function setOverride(k: string, v: string) {
    const next = { ...overrides };
    if (v) next[k] = v; else delete next[k];
    set({ theme: { ...theme, overrides: next } });
  }

  function normalizeHex(hex: string): string {
    if (!hex) return "#000000";
    if (hex.length === 9) return hex.slice(0, 7);
    if (hex.length === 4) return "#" + [...hex.slice(1)].map(c => c+c).join("");
    return hex;
  }

  $: tokens = Object.entries(palette).filter(([, v]) => typeof v === "string" && /^#[0-9a-fA-F]{3,8}$/.test(v));
</script>

<div class="section">
  <Sub num={1} title="Theme" desc="Active colour theme for the top bar and panels. Matugen adapts the palette to your wallpaper in real time.">
    <div class="variant-grid">
      {#each VARIANTS as v}
        <button type="button" class="variant" class:active={s.topbarTheme === v.id} on:click={() => set({ topbarTheme: v.id })}>
          <div class="stripe">
            {#each v.colors as c}<span style="background:{c}" />{/each}
          </div>
          <div class="name">{v.name}</div>
          <div class="desc">{v.desc}</div>
        </button>
      {/each}
    </div>
  </Sub>

  <Sub num={2} title="Interface scale" desc="Global multiplier from 0.5× to 2.0×. Applies without restarting the shell.">
    <Row label="UI scale" code="qs.uiScale">
      <Slider value={+(s.uiScale ?? 1).toFixed(2)} min={0.5} max={2} step={0.05} unit="×"
              onChange={(v) => set({ uiScale: v })} />
    </Row>
  </Sub>

  <Sub num={3} title="Palette overrides" desc="Pin individual qs_colors.json tokens. Empty values fall back to matugen output.">
    <svelte:fragment slot="right">
      {#if Object.keys(overrides).length > 0}
        <button class="btn ghost" on:click={() => set({ theme: { ...theme, overrides: {} } })}>
          <Icon name="discard" size={12} /> Reset {Object.keys(overrides).length}
        </button>
      {/if}
    </svelte:fragment>

    {#if tokens.length === 0}
      <div class="empty">qs_colors.json not detected.</div>
    {:else}
      <div class="swatch-grid">
        {#each tokens as [k, v]}
          {@const cur = overrides[k] || v}
          <label class="swatch" class:overridden={!!overrides[k]}>
            <input type="color" value={normalizeHex(cur)} on:change={(e) => setOverride(k, e.currentTarget.value)} />
            <div class="swatch-meta">
              <span class="name">{k}</span>
              <span class="hex">{cur.toUpperCase()}</span>
            </div>
          </label>
        {/each}
      </div>
    {/if}
  </Sub>

  <Sub num={4} title="Wallpaper & startup">
    <Row label="Wallpaper directory" hint="Scanned by the wallpaper picker">
      <input type="text" value={s.wallpaperDir || ""} on:input={(e) => set({ wallpaperDir: e.currentTarget.value })} style="width:320px" />
    </Row>
    <Row label="Show hello popup on startup" hint="Opens the onboarding screen on login">
      <Toggle checked={!!s.openGuideAtStartup} on:change={(e) => set({ openGuideAtStartup: e.detail })} />
    </Row>
  </Sub>
</div>

// config-ui/src/sections/ThemeSection.tsx
import React from "react";
import { Settings } from "../api";
import { Sub, Row, Toggle, Slider } from "../components/UI";
import { Icon } from "../components/Icon";

const VARIANTS = [
  { id: "mocha",     name: "Mocha",     desc: "Warm night",  colors: ["#1e1e2e", "#cba6f7", "#89b4fa", "#fab387"] },
  { id: "macchiato", name: "Macchiato", desc: "Deep steam",  colors: ["#24273a", "#c6a0f6", "#8aadf4", "#f5a97f"] },
  { id: "frappe",    name: "Frappé",    desc: "Milk coffee", colors: ["#303446", "#ca9ee6", "#8caaee", "#ef9f76"] },
  { id: "latte",     name: "Latte",     desc: "Bright day",  colors: ["#eff1f5", "#8839ef", "#1e66f5", "#fe640b"] },
];

export function ThemeSection({
  s,
  set,
  palette,
}: {
  s: Settings;
  set: (p: Partial<Settings>) => void;
  palette: Record<string, string>;
}) {
  const theme = s.theme ?? { mode: s.topbarTheme || "mocha", overrides: {} };
  const setTheme = (p: Partial<typeof theme>) => set({ theme: { ...theme, ...p } });
  const overrides = theme.overrides || {};
  const setOverride = (k: string, v: string) => {
    const next = { ...overrides };
    if (v) next[k] = v;
    else delete next[k];
    setTheme({ overrides: next });
  };

  const tokens = Object.entries(palette).filter(
    ([, v]) => typeof v === "string" && /^#[0-9a-fA-F]{3,8}$/.test(v),
  );

  return (
    <div className="section">
      <Sub
        num={1}
        title="Catppuccin flavour"
        desc="Base flavour for the top bar and panels. Matugen layers extracted colors on top in real time."
      >
        <div className="variant-grid">
          {VARIANTS.map((v) => (
            <div
              key={v.id}
              className={"variant" + (s.topbarTheme === v.id ? " active" : "")}
              onClick={() => set({ topbarTheme: v.id, theme: { ...theme, mode: v.id } })}
            >
              <div className="stripe">
                {v.colors.map((c, i) => (
                  <span key={i} style={{ background: c }} />
                ))}
              </div>
              <div className="name">{v.name}</div>
              <div className="desc">{v.desc}</div>
            </div>
          ))}
        </div>
      </Sub>

      <Sub
        num={2}
        title="Interface scale"
        desc="Global multiplier from 0.5× to 2.0×. Applies without restarting the shell."
      >
        <Row label="UI scale" code="qs.uiScale">
          <Slider
            value={+(s.uiScale ?? 1).toFixed(2)}
            min={0.5}
            max={2}
            step={0.05}
            unit="×"
            onChange={(v) => set({ uiScale: v })}
          />
        </Row>
      </Sub>

      <Sub
        num={3}
        title="Palette overrides"
        desc="Pin individual qs_colors.json tokens. Empty values fall back to matugen output."
        right={
          Object.keys(overrides).length > 0 && (
            <button className="btn ghost" onClick={() => setTheme({ overrides: {} })}>
              <Icon name="discard" size={12} /> Reset {Object.keys(overrides).length}
            </button>
          )
        }
      >
        {tokens.length === 0 ? (
          <div className="empty">qs_colors.json not detected.</div>
        ) : (
          <div className="swatch-grid">
            {tokens.map(([k, v]) => {
              const cur = overrides[k] || v;
              return (
                <label key={k} className={"swatch" + (overrides[k] ? " overridden" : "")}>
                  <input
                    type="color"
                    value={normalizeHex(cur)}
                    onChange={(e) => setOverride(k, e.target.value)}
                  />
                  <div className="swatch-meta">
                    <span className="name">{k}</span>
                    <span className="hex">{cur.toUpperCase()}</span>
                  </div>
                </label>
              );
            })}
          </div>
        )}
      </Sub>

      <Sub num={4} title="Wallpaper & startup">
        <Row label="Wallpaper directory" hint="Scanned by the wallpaper picker">
          <input
            type="text"
            value={s.wallpaperDir || ""}
            onChange={(e) => set({ wallpaperDir: e.target.value })}
            style={{ width: 320 }}
          />
        </Row>
        <Row label="Top bar help icon">
          <Toggle on={!!s.topbarHelpIcon} onChange={(v) => set({ topbarHelpIcon: v })} />
        </Row>
        <Row label="Open guide on first run">
          <Toggle on={!!s.openGuideAtStartup} onChange={(v) => set({ openGuideAtStartup: v })} />
        </Row>
      </Sub>
    </div>
  );
}

function normalizeHex(s: string): string {
  if (!s) return "#000000";
  if (s.length === 9) return s.slice(0, 7);
  if (s.length === 4) return "#" + [...s.slice(1)].map((c) => c + c).join("");
  return s;
}
